#!/bin/bash
set -euo pipefail

: "${REPOSITORY:?REPOSITORY is required}"
: "${RELEASE_TAG:?RELEASE_TAG is required}"
: "${OUTPUT:?OUTPUT is required}"

pkgname="tor-pt"

version="${RELEASE_TAG#v}"

if [[ "$version" =~ ^(.+)-([0-9]+)$ ]]; then
    pkgver="${BASH_REMATCH[1]}"
    pkgrel="${BASH_REMATCH[2]}"
else
    pkgver="$version"
    pkgrel=1
fi

# Convert the Git tag into a valid Arch package version.
pkgver="${pkgver//[^a-zA-Z0-9.+_]/_}"

mapfile -t tarballs < <(
    find .release \
        -maxdepth 1 \
        -type f \
        -name '*.tar.gz' \
        -printf '%f\n' |
        sort
)

if ((${#tarballs[@]} == 0)); then
    echo "No release tarballs found" >&2
    exit 1
fi

{
    cat << EOF
# Generated by GitHub Actions.
# Do not edit manually.

pkgname='${pkgname}'
pkgver='${pkgver}'
pkgrel=${pkgrel}
pkgdesc='Collection of pluggable transports for Tor'
arch=('x86_64')
url='https://github.com/${REPOSITORY}'
license=('MIT')
depends=('tor')

source=(
EOF

    for tarball in "${tarballs[@]}"; do
        printf "  'https://github.com/%s/releases/download/%s/%s'\n" \
            "$REPOSITORY" \
            "$RELEASE_TAG" \
            "$tarball"
    done

    cat << 'EOF'
)

sha256sums=(
EOF

    for tarball in "${tarballs[@]}"; do
        printf "  '%s'\n" \
            "$(grep -F "$tarball" .release/SHA256SUMS | cut -d ' ' -f 1)"
    done

    cat << 'EOF'
)

package() {
  install -dm755 "$pkgdir/usr/lib/tor-pt"

  while IFS= read -r -d '' file; do
    filename="$(basename "$file")"
    destination="$pkgdir/usr/lib/tor-pt/$filename"

    if [[ -e "$destination" ]]; then
      printf 'error: duplicate transport filename: %s\n' "$filename" >&2
      return 1
    fi

    install -Dm755 "$file" "$destination"
  done < <(
    find "$srcdir" \
      -type f \
      -perm /111 \
      -print0
  )
}
EOF
} > "$OUTPUT"

echo "Generated $OUTPUT"
