# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Code quality

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: apk add --no-cache make shellcheck shfmt
      - name: Run CI
        run: make ci
